lease_web_excel:
    resource: "@LeaseWebExcelBundle/Resources/config/routing.yml"
    prefix:   /

lease_web_customer:
    resource: "@LeaseWebCustomerBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
